version: 2
jobs: 
  build:
    docker:
      - image: circleci/golang:1.12 #
    working_directory: /go/src/github.com/nozo-moto/taskqueue
    steps:
        - checkout
        - run:
            name: build
            command: go build
